#!/usr/bin/env python3
"""Render an OTLP HTTP bridge fallback that writes logs/traces directly to Elasticsearch."""

from __future__ import annotations


def render_bridge_script(*, es_url: str, index_prefix: str, bind_host: str, bind_port: int, verify_tls: bool) -> str:
    events_data_stream = f"{index_prefix}-events"
    verify_tls_literal = "True" if verify_tls else "False"
    return f'''#!/usr/bin/env python3
"""Auto-generated OTLP HTTP bridge fallback.

This bridge accepts OTLP HTTP `POST /v1/logs` and `POST /v1/traces` payloads,
then writes normalized documents directly into Elasticsearch data stream
`{events_data_stream}`.

Generated by: elasticsearch-agent-observability
"""

from __future__ import annotations

import base64
import json
import os
import ssl
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any
from urllib import error, request

ES_URL = {es_url!r}
EVENTS_DATA_STREAM = {events_data_stream!r}
BRIDGE_HOST = {bind_host!r}
BRIDGE_PORT = {bind_port}
VERIFY_TLS = {verify_tls_literal}
MAX_BODY_SIZE = 50 * 1024 * 1024  # 50 MB — reject oversized payloads to prevent DoS

# Sensitive GenAI fields that should be stripped before writing to ES.
# The ingest pipeline also removes these, but defence-in-depth is safer.
_REDACT_KEYS = {{"gen_ai.prompt", "gen_ai.completion", "gen_ai.tool.call.arguments", "gen_ai.tool.call.result"}}


class BridgeServer(ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _ns_to_iso(value: Any) -> str:
    text = str(value or "").strip()
    if not text:
        return _now_iso()
    try:
        nanos = int(text)
    except (TypeError, ValueError):
        return _now_iso()
    seconds, remainder = divmod(max(nanos, 0), 1_000_000_000)
    stamp = datetime.fromtimestamp(seconds, tz=timezone.utc).replace(microsecond=remainder // 1000)
    return stamp.isoformat().replace("+00:00", "Z")


def _parse_any_value(value: Any) -> Any:
    if not isinstance(value, dict):
        return value
    if "stringValue" in value:
        return value["stringValue"]
    if "boolValue" in value:
        return value["boolValue"]
    if "intValue" in value:
        text = value["intValue"]
        try:
            return int(text)
        except (TypeError, ValueError):
            return text
    if "doubleValue" in value:
        return value["doubleValue"]
    if "bytesValue" in value:
        return value["bytesValue"]
    if "arrayValue" in value:
        return [_parse_any_value(item) for item in value["arrayValue"].get("values", [])]
    if "kvlistValue" in value:
        return _collect_attributes(value["kvlistValue"].get("values", []))
    return value


def _collect_attributes(items: Any) -> dict[str, Any]:
    attributes: dict[str, Any] = {{}}
    if not isinstance(items, list):
        return attributes
    for item in items:
        if not isinstance(item, dict):
            continue
        key = str(item.get("key") or "").strip()
        if not key:
            continue
        attributes[key] = _parse_any_value(item.get("value"))
    return attributes


def _merge_attributes(*groups: dict[str, Any]) -> dict[str, Any]:
    merged: dict[str, Any] = {{}}
    for group in groups:
        for key, value in group.items():
            if value is None:
                continue
            merged[key] = value
    return merged


def _signal_blocks(payload: dict[str, Any], signal: str) -> list[dict[str, Any]]:
    key = "resourceLogs" if signal == "logs" else "resourceSpans"
    value = payload.get(key, [])
    return value if isinstance(value, list) else []


def _decode_payload(body: bytes, *, signal: str, content_type: str) -> dict[str, Any]:
    lowered = content_type.lower()
    if "application/json" in lowered:
        return json.loads(body.decode("utf-8"))
    if "application/x-protobuf" in lowered or "application/octet-stream" in lowered:
        return _decode_protobuf_payload(body, signal=signal)
    # No explicit content-type — fall back to body sniffing.
    if not lowered.strip() and body.lstrip().startswith(b"{{"):
        return json.loads(body.decode("utf-8"))
    raise ValueError(f"Unsupported OTLP content type: {{content_type or 'unknown'}}")


def _decode_protobuf_payload(body: bytes, *, signal: str) -> dict[str, Any]:
    try:
        from google.protobuf.json_format import MessageToDict
        if signal == "logs":
            from opentelemetry.proto.collector.logs.v1.logs_service_pb2 import ExportLogsServiceRequest

            message = ExportLogsServiceRequest()
        else:
            from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import ExportTraceServiceRequest

            message = ExportTraceServiceRequest()
    except ImportError as exc:
        raise ValueError(
            "OTLP protobuf payloads require `google.protobuf` and `opentelemetry-proto` at runtime; send OTLP JSON or install the proto packages first."
        ) from exc
    message.ParseFromString(body)
    return MessageToDict(message, preserving_proto_field_name=True)


def _coerce_message(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return json.dumps(value, ensure_ascii=False, sort_keys=True)


def _apply_attributes(document: dict[str, Any], attributes: dict[str, Any]) -> None:
    for key, value in attributes.items():
        if not key or value is None or key in document or key in _REDACT_KEYS:
            continue
        document[key] = value


def _status_to_outcome(status: Any) -> str | None:
    code = None
    if isinstance(status, dict):
        code = status.get("code")
    if isinstance(code, str):
        normalized = code.upper()
        if normalized.endswith("ERROR"):
            return "failure"
        if normalized.endswith("OK"):
            return "success"
        return None
    if code == 2:
        return "failure"
    if code == 1:
        return "success"
    return None


def _span_kind(value: Any) -> str | None:
    if isinstance(value, str):
        normalized = value.split("_")[-1].lower()
        return normalized or None
    if value == 1:
        return "internal"
    if value == 2:
        return "server"
    if value == 3:
        return "client"
    if value == 4:
        return "producer"
    if value == 5:
        return "consumer"
    return None


def _iter_log_documents(payload: dict[str, Any]) -> list[dict[str, Any]]:
    documents: list[dict[str, Any]] = []
    for resource_block in _signal_blocks(payload, "logs"):
        resource_attributes = _collect_attributes((resource_block.get("resource") or {{}}).get("attributes", []))
        scope_blocks = resource_block.get("scopeLogs") or resource_block.get("instrumentationLibraryLogs") or []
        for scope_block in scope_blocks:
            scope = scope_block.get("scope") or scope_block.get("instrumentationLibrary") or {{}}
            scope_name = str(scope.get("name") or "").strip()
            scope_version = str(scope.get("version") or "").strip()
            scope_attributes = _collect_attributes(scope.get("attributes", []))
            for record in scope_block.get("logRecords", []):
                record_attributes = _collect_attributes(record.get("attributes", []))
                merged = _merge_attributes(resource_attributes, scope_attributes, record_attributes)
                body = _parse_any_value(record.get("body"))
                document = {{
                    "@timestamp": _ns_to_iso(record.get("timeUnixNano") or record.get("time_unix_nano") or record.get("observedTimeUnixNano") or record.get("observed_time_unix_nano")),
                    "observer.ingest_path": "otlphttpbridge",
                    "observer.transport": "otlp_http",
                    "observer.type": "bridge",
                    "otel.signal": "logs",
                    "event.kind": "event",
                    "event.action": merged.get("event.action") or "otlp.log",
                    "service.name": merged.get("service.name") or "unknown-service",
                }}
                if scope_name:
                    document["otel.scope.name"] = scope_name
                if scope_version:
                    document["otel.scope.version"] = scope_version
                severity_text = str(record.get("severityText") or record.get("severity_text") or "").strip()
                if severity_text:
                    document["log.level"] = severity_text.lower()
                trace_id = str(record.get("traceId") or record.get("trace_id") or "").strip()
                if trace_id:
                    document["trace.id"] = trace_id.lower()
                span_id = str(record.get("spanId") or record.get("span_id") or "").strip()
                if span_id:
                    document["span.id"] = span_id.lower()
                message = _coerce_message(body)
                if message:
                    document["message"] = message
                if not isinstance(body, str) and body is not None:
                    document["log.body"] = body
                _apply_attributes(document, merged)
                documents.append(document)
    return documents


def _iter_trace_documents(payload: dict[str, Any]) -> list[dict[str, Any]]:
    documents: list[dict[str, Any]] = []
    for resource_block in _signal_blocks(payload, "traces"):
        resource_attributes = _collect_attributes((resource_block.get("resource") or {{}}).get("attributes", []))
        scope_blocks = resource_block.get("scopeSpans") or resource_block.get("instrumentationLibrarySpans") or []
        for scope_block in scope_blocks:
            scope = scope_block.get("scope") or scope_block.get("instrumentationLibrary") or {{}}
            scope_name = str(scope.get("name") or "").strip()
            scope_version = str(scope.get("version") or "").strip()
            scope_attributes = _collect_attributes(scope.get("attributes", []))
            for span in scope_block.get("spans", []):
                span_attributes = _collect_attributes(span.get("attributes", []))
                merged = _merge_attributes(resource_attributes, scope_attributes, span_attributes)
                start_ns_text = span.get("startTimeUnixNano") or span.get("start_time_unix_nano")
                end_ns_text = span.get("endTimeUnixNano") or span.get("end_time_unix_nano")
                try:
                    start_ns = int(start_ns_text) if start_ns_text else 0
                except (TypeError, ValueError):
                    start_ns = 0
                try:
                    end_ns = int(end_ns_text) if end_ns_text else 0
                except (TypeError, ValueError):
                    end_ns = 0
                name = str(span.get("name") or "").strip()
                document = {{
                    "@timestamp": _ns_to_iso(start_ns or end_ns),
                    "observer.ingest_path": "otlphttpbridge",
                    "observer.transport": "otlp_http",
                    "observer.type": "bridge",
                    "otel.signal": "traces",
                    "event.kind": "event",
                    "event.action": merged.get("event.action") or name or "otlp.span",
                    "service.name": merged.get("service.name") or "unknown-service",
                }}
                if scope_name:
                    document["otel.scope.name"] = scope_name
                if scope_version:
                    document["otel.scope.version"] = scope_version
                if name:
                    document["span.name"] = name
                    document.setdefault("message", name)
                kind = _span_kind(span.get("kind"))
                if kind:
                    document["span.kind"] = kind
                trace_id = str(span.get("traceId") or span.get("trace_id") or "").strip()
                if trace_id:
                    document["trace.id"] = trace_id.lower()
                span_id = str(span.get("spanId") or span.get("span_id") or "").strip()
                if span_id:
                    document["span.id"] = span_id.lower()
                parent_id = str(span.get("parentSpanId") or span.get("parent_span_id") or "").strip()
                if parent_id:
                    document["parent.id"] = parent_id.lower()
                outcome = merged.get("event.outcome") or _status_to_outcome(span.get("status"))
                if outcome:
                    document["event.outcome"] = outcome
                if end_ns and start_ns and end_ns >= start_ns:
                    document["event.duration"] = end_ns - start_ns
                _apply_attributes(document, merged)
                documents.append(document)
    return documents


def _es_request_context():
    if ES_URL.startswith("https://") and not VERIFY_TLS:
        return ssl._create_unverified_context()
    return None


def _post_document(document: dict[str, Any]) -> None:
    _post_documents([document])


def _post_documents(documents: list[dict[str, Any]]) -> None:
    if not documents:
        return
    endpoint = f"{{ES_URL.rstrip('/')}}/{{EVENTS_DATA_STREAM}}/_bulk"
    lines: list[str] = []
    for doc in documents:
        lines.append(json.dumps({{"create": {{}}}}, separators=(",", ":")))
        lines.append(json.dumps(doc, ensure_ascii=False))
    payload = ("\\n".join(lines) + "\\n").encode("utf-8")
    req = request.Request(endpoint, data=payload, method="POST")
    req.add_header("Content-Type", "application/x-ndjson")
    username = os.environ.get("ELASTICSEARCH_USERNAME", "").strip()
    if username:
        password = os.environ.get("ELASTICSEARCH_PASSWORD", "")
        token = base64.b64encode(f"{{username}}:{{password}}".encode("utf-8")).decode("ascii")
        req.add_header("Authorization", f"Basic {{token}}")
    try:
        with request.urlopen(req, timeout=30, context=_es_request_context()) as response:
            if response.status not in {{200, 201}}:
                raise RuntimeError(f"Elasticsearch _bulk returned unexpected status {{response.status}}")
    except error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Elasticsearch _bulk failed: HTTP {{exc.code}} {{body}}") from exc


class OTLPBridgeHandler(BaseHTTPRequestHandler):
    server_version = "otlphttpbridge/1.0"

    def log_message(self, fmt: str, *args: Any) -> None:
        print(f"[otlphttpbridge] {{self.address_string()}} - {{fmt % args}}")

    def _write_json(self, status: int, payload: dict[str, Any]) -> None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:
        if self.path.split("?", 1)[0] == "/healthz":
            self._write_json(200, {{"status": "ok", "events_data_stream": EVENTS_DATA_STREAM}})
            return
        self._write_json(404, {{"error": "not found"}})

    def do_POST(self) -> None:
        route = self.path.split("?", 1)[0]
        if route == "/v1/metrics":
            self._write_json(501, {{"error": "bridge fallback only supports logs and traces; keep metrics on the Collector path."}})
            return
        if route not in {{"/v1/logs", "/v1/traces"}}:
            self._write_json(404, {{"error": "not found"}})
            return
        signal = "logs" if route.endswith("logs") else "traces"
        content_length = int(self.headers.get("Content-Length", "0") or "0")
        if content_length > MAX_BODY_SIZE:
            self._write_json(413, {{"error": f"payload too large ({{content_length}} bytes, max {{MAX_BODY_SIZE}})" }})
            return
        body = self.rfile.read(content_length)
        try:
            payload = _decode_payload(body, signal=signal, content_type=self.headers.get("Content-Type", ""))
            documents = _iter_log_documents(payload) if signal == "logs" else _iter_trace_documents(payload)
            if documents:
                _post_documents(documents)
            self._write_json(
                200,
                {{
                    "accepted": len(documents),
                    "signal": signal,
                    "events_data_stream": EVENTS_DATA_STREAM,
                    "bridge": f"http://{{BRIDGE_HOST}}:{{BRIDGE_PORT}}",
                }},
            )
        except ValueError as exc:
            self._write_json(400, {{"error": str(exc)}})
        except Exception as exc:  # noqa: BLE001
            self._write_json(500, {{"error": str(exc)}})


def main() -> int:
    server = BridgeServer((BRIDGE_HOST, BRIDGE_PORT), OTLPBridgeHandler)
    print(f"OTLP HTTP bridge listening on http://{{BRIDGE_HOST}}:{{BRIDGE_PORT}} -> {{ES_URL.rstrip('/')}}/{{EVENTS_DATA_STREAM}}")
    server.serve_forever()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''
