#!/usr/bin/env python3
"""Generate auto-instrumentation code snippets for discovered agent modules.

This produces a ready-to-use Python starter file that wires OpenTelemetry
TracerProvider + MeterProvider + LogHandler to the Collector endpoint.
The user drops it into their agent entrypoint or imports it as a side-effect module.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from common import SkillError, ensure_dir, print_error, read_json, write_text

_HEADER = '''\
"""Auto-generated OpenTelemetry instrumentation bootstrap.

Drop this file into your agent project and import it early in your entrypoint:

    import agent_otel_bootstrap  # noqa: F401

Or call `setup()` explicitly for more control.

Generated by: elasticsearch-agent-observability
"""

from __future__ import annotations

import os
import logging

'''

_SETUP_FUNCTION = '''\
def setup(
    *,
    service_name: str | None = None,
    otlp_endpoint: str | None = None,
    environment: str | None = None,
) -> None:
    """Initialize OpenTelemetry tracing, metrics, and logging export."""
    _service = service_name or os.environ.get("OTEL_SERVICE_NAME", "{service_name}")
    _endpoint = otlp_endpoint or os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT", "{otlp_endpoint}")
    _env = environment or os.environ.get("OTEL_RESOURCE_ENVIRONMENT", "{environment}")

    try:
        from opentelemetry import trace, metrics
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor
        from opentelemetry.sdk.metrics import MeterProvider
        from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
        from opentelemetry.sdk.resources import Resource
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
        from opentelemetry.exporter.otlp.proto.grpc.metric_exporter import OTLPMetricExporter
    except ImportError:
        logging.warning("opentelemetry SDK not installed; skipping auto-instrumentation. pip install opentelemetry-sdk opentelemetry-exporter-otlp-proto-grpc")
        return

    resource = Resource.create({{
        "service.name": _service,
        "deployment.environment": _env,
        "observer.product": "elasticsearch-agent-observability",
    }})

    # --- Tracing ---
    tracer_provider = TracerProvider(resource=resource)
    tracer_provider.add_span_processor(
        BatchSpanProcessor(OTLPSpanExporter(endpoint=_endpoint, insecure=_endpoint.startswith("http://")))
    )
    trace.set_tracer_provider(tracer_provider)

    # --- Metrics ---
    metric_reader = PeriodicExportingMetricReader(
        OTLPMetricExporter(endpoint=_endpoint, insecure=_endpoint.startswith("http://")),
        export_interval_millis=15000,
    )
    meter_provider = MeterProvider(resource=resource, metric_readers=[metric_reader])
    metrics.set_meter_provider(meter_provider)

    # --- Logging (optional, requires opentelemetry-sdk >= 1.24) ---
    try:
        from opentelemetry.sdk._logs import LoggerProvider, LoggingHandler
        from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
        from opentelemetry.exporter.otlp.proto.grpc._log_exporter import OTLPLogExporter

        logger_provider = LoggerProvider(resource=resource)
        logger_provider.add_log_record_processor(
            BatchLogRecordProcessor(OTLPLogExporter(endpoint=_endpoint, insecure=_endpoint.startswith("http://")))
        )
        handler = LoggingHandler(level=logging.INFO, logger_provider=logger_provider)
        logging.getLogger().addHandler(handler)
    except ImportError:
        pass  # Log export is optional


# Auto-setup on import
setup()
'''

_TOOL_WRAPPER = '''

# --- Convenience wrappers for common agent operations ---

def traced_tool_call(tool_name: str):
    """Decorator that wraps a tool function with an OTel span."""
    def decorator(func):
        def wrapper(*args, **kwargs):
            try:
                from opentelemetry import trace
                tracer = trace.get_tracer("agent-observability")
            except ImportError:
                return func(*args, **kwargs)
            with tracer.start_as_current_span(
                f"tool.{tool_name}",
                attributes={
                    "gen_ai.agent.tool_name": tool_name,
                    "gen_ai.agent.signal_type": "tool_call",
                },
            ) as span:
                try:
                    result = func(*args, **kwargs)
                    span.set_attribute("event.outcome", "success")
                    return result
                except Exception as exc:
                    span.set_attribute("event.outcome", "failure")
                    span.set_attribute("gen_ai.agent.error_type", type(exc).__name__)
                    span.record_exception(exc)
                    raise
        wrapper.__name__ = func.__name__
        wrapper.__doc__ = func.__doc__
        return wrapper
    return decorator


def traced_model_call(model_name: str):
    """Decorator that wraps an LLM call with an OTel span."""
    def decorator(func):
        def wrapper(*args, **kwargs):
            try:
                from opentelemetry import trace
                tracer = trace.get_tracer("agent-observability")
            except ImportError:
                return func(*args, **kwargs)
            with tracer.start_as_current_span(
                f"model.{model_name}",
                attributes={
                    "gen_ai.agent.model_name": model_name,
                    "gen_ai.agent.signal_type": "model_call",
                },
            ) as span:
                try:
                    result = func(*args, **kwargs)
                    span.set_attribute("event.outcome", "success")
                    if isinstance(result, dict):
                        if "usage" in result:
                            usage = result["usage"]
                            span.set_attribute("gen_ai.usage.input_tokens", usage.get("prompt_tokens", 0))
                            span.set_attribute("gen_ai.usage.output_tokens", usage.get("completion_tokens", 0))
                    return result
                except Exception as exc:
                    span.set_attribute("event.outcome", "failure")
                    span.set_attribute("gen_ai.agent.error_type", type(exc).__name__)
                    span.record_exception(exc)
                    raise
        wrapper.__name__ = func.__name__
        wrapper.__doc__ = func.__doc__
        return wrapper
    return decorator
'''


def render_instrument_snippet(
    discovery: dict[str, Any],
    *,
    service_name: str,
    environment: str,
    otlp_endpoint: str,
    index_prefix: str,
) -> str:
    modules = {module.get("module_kind") for module in discovery.get("detected_modules", []) if module.get("module_kind")}
    parts = [_HEADER]
    parts.append(
        _SETUP_FUNCTION.format(
            service_name=service_name,
            otlp_endpoint=otlp_endpoint,
            environment=environment,
        )
    )
    if {"tool_registry", "model_adapter", "mcp_surface", "runtime_entrypoint"} & modules:
        parts.append(_TOOL_WRAPPER)
    return "".join(parts)


def render_snippet_to_file(
    discovery: dict[str, Any],
    output_path: Path,
    *,
    service_name: str,
    environment: str,
    otlp_endpoint: str,
    index_prefix: str,
) -> Path:
    snippet = render_instrument_snippet(
        discovery,
        service_name=service_name,
        environment=environment,
        otlp_endpoint=otlp_endpoint,
        index_prefix=index_prefix,
    )
    ensure_dir(output_path.parent)
    write_text(output_path, snippet)
    return output_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate auto-instrumentation snippet")
    parser.add_argument("--discovery", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--service-name", default="agent-runtime")
    parser.add_argument("--environment", default="dev")
    parser.add_argument("--otlp-endpoint", default="http://127.0.0.1:4317")
    parser.add_argument("--index-prefix", default="agent-obsv")
    return parser.parse_args()


def main() -> int:
    try:
        args = parse_args()
        discovery = read_json(Path(args.discovery).expanduser().resolve())
        output = render_snippet_to_file(
            discovery,
            Path(args.output).expanduser().resolve(),
            service_name=args.service_name,
            environment=args.environment,
            otlp_endpoint=args.otlp_endpoint,
            index_prefix=args.index_prefix,
        )
        print(f"✅ instrumentation snippet written: {output}")
        return 0
    except SkillError as exc:
        print_error(str(exc))
        return 1
    except Exception as exc:  # noqa: BLE001
        print_error(f"Failed to generate instrumentation snippet: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
