#!/usr/bin/env python3
"""Generate an LLM proxy starter bundle.

The LLM proxy pattern puts a tracing-aware reverse proxy in front of the
OpenAI / Anthropic / Azure OpenAI endpoints. The target agent (e.g. an
upstream OSS project you do not want to fork) just points its
``OPENAI_API_BASE`` / ``ANTHROPIC_BASE_URL`` at the proxy — and the proxy
emits OTel spans with ``gen_ai.*`` attributes that the rest of this skill's
pipeline already knows how to visualize and alert on.

Bundle layout::

    llm-proxy/
    ├── docker-compose.yaml        # litellm + shared network to the Collector
    ├── config.yaml                # LiteLLM config with model aliases
    ├── .env.example               # Upstream API keys + OTLP endpoint
    └── README.md                  # Zero-code integration guide
"""

from __future__ import annotations

import argparse
from pathlib import Path

from common import SkillError, ensure_dir, print_error, write_text


_DOCKER_COMPOSE = """\
# Auto-generated by elasticsearch-agent-observability.
# Put a tracing-aware LLM proxy in front of OpenAI / Anthropic so any agent
# pointing at this proxy becomes observable without touching its source code.

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    container_name: agent-obsv-llm-proxy
    restart: unless-stopped
    ports:
      - "{proxy_port}:4000"
    env_file:
      - .env
    environment:
      OTEL_SERVICE_NAME: "{service_name}-proxy"
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment={environment},observer.product=elasticsearch-agent-observability"
      OTEL_EXPORTER_OTLP_ENDPOINT: "${{OTEL_EXPORTER_OTLP_ENDPOINT:-http://host.docker.internal:4317}}"
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      LITELLM_LOG: info
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    extra_hosts:
      # Lets the container reach a Collector running on the host on Linux.
      - "host.docker.internal:host-gateway"
"""


_LITELLM_CONFIG = """\
# LiteLLM routing config. Add more model aliases here as needed.
# Any call to /chat/completions with one of these model names will be routed
# to the upstream provider listed under `litellm_params`.

model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY

general_settings:
  # LiteLLM emits OTel spans automatically when these env vars are set
  # (see .env.example). No code changes needed on the agent side.
  telemetry: true

litellm_settings:
  callbacks: ["otel"]
  success_callback: ["otel"]
  failure_callback: ["otel"]
"""


_ENV_EXAMPLE = """\
# Copy to .env and fill in.

# --- Upstream provider keys ---
OPENAI_API_KEY=sk-...
ANTHROPIC_API_KEY=sk-ant-...

# --- Where the proxy sends telemetry ---
# Default assumes the OTel Collector generated by this skill is running on
# the host machine. Adjust if the Collector lives elsewhere.
OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317

# --- Proxy listen port (on the host) ---
# Matches `ports` in docker-compose.yaml. Agents will talk to
# http://localhost:<PROXY_PORT>/v1
"""


_README = """\
# LLM proxy starter

## What this solves

Your target agent is an **upstream project you do not want to fork**
(for example, `openclaw/openclaw` or any other third-party agent runtime).
You can't add OTel SDK calls into someone else's source tree, but you still
want per-model latency, token usage, and error rates for the calls it makes.

This bundle runs a tracing-aware LLM proxy (LiteLLM) in front of OpenAI /
Anthropic. The agent points at the proxy. The proxy emits OTel spans to the
Collector that `bootstrap_observability.py` already generated. Done.

## Start the proxy

```bash
cp .env.example .env
# edit .env: paste the upstream API keys
docker compose up -d
docker compose logs -f litellm
```

Default listen URL: `http://localhost:{proxy_port}`.

## Point your agent at it

For any OpenAI-SDK-compatible agent (including OpenClaw), set:

```bash
export OPENAI_API_BASE=http://localhost:{proxy_port}/v1
export OPENAI_API_KEY=sk-anything       # LiteLLM will override with its own
```

For Anthropic-native clients:

```bash
export ANTHROPIC_BASE_URL=http://localhost:{proxy_port}
```

Then restart the agent. That's it.

## What you will see in Kibana

Once the Collector is running and the proxy is proxying real traffic,
open the generated dashboard. You should see:

- **Model call latency (p50 / p95)** per `gen_ai.request.model`
- **Input / output token totals** per model
- **Error rate** by upstream status code
- **Request volume** over time

The alert rules in `scripts/alert_and_diagnose.py` will trigger on
token-anomaly, latency-degradation, and error-rate-spike the same as for
instrumented code.

## What you will **not** see via the proxy

The proxy is outside the agent, so it cannot distinguish:

- which **tool call** triggered a model call
- which **session** / **turn** the call belongs to
- retries at the agent orchestration layer

If you need those dimensions, the agent has to propagate them as HTTP
headers (LiteLLM forwards arbitrary headers into span attributes via
`litellm_headers_to_span_attributes`). Ask your agent vendor to expose a
hook, or wrap the call site yourself.

## Zero-code checklist

- [ ] `.env` populated with `OPENAI_API_KEY` / `ANTHROPIC_API_KEY`
- [ ] Collector running (from `run-collector.sh`)
- [ ] `docker compose up -d` succeeded
- [ ] Agent env updated (`OPENAI_API_BASE` / `ANTHROPIC_BASE_URL`)
- [ ] Agent restarted
- [ ] Kibana dashboard shows fresh data

## Rollback

```bash
docker compose down
# then unset the OPENAI_API_BASE / ANTHROPIC_BASE_URL on the agent side
```

No code was changed in the agent, so there is nothing else to undo.
"""


def render_llm_proxy_bundle(
    output_dir: Path,
    *,
    service_name: str,
    environment: str,
    proxy_port: int = 4000,
) -> dict[str, Path]:
    ensure_dir(output_dir)
    compose_path = output_dir / "docker-compose.yaml"
    config_path = output_dir / "config.yaml"
    env_path = output_dir / ".env.example"
    readme_path = output_dir / "README.md"
    write_text(
        compose_path,
        _DOCKER_COMPOSE.format(
            proxy_port=proxy_port,
            service_name=service_name,
            environment=environment,
        ),
    )
    write_text(config_path, _LITELLM_CONFIG)
    write_text(env_path, _ENV_EXAMPLE)
    write_text(readme_path, _README.format(proxy_port=proxy_port))
    return {
        "compose": compose_path,
        "config": config_path,
        "env_example": env_path,
        "readme": readme_path,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate an LLM proxy starter bundle")
    parser.add_argument("--output-dir", required=True, help="Target directory for the llm-proxy/ bundle")
    parser.add_argument("--service-name", default="agent-runtime")
    parser.add_argument("--environment", default="dev")
    parser.add_argument("--proxy-port", type=int, default=4000)
    return parser.parse_args()


def main() -> int:
    try:
        args = parse_args()
        paths = render_llm_proxy_bundle(
            Path(args.output_dir).expanduser().resolve(),
            service_name=args.service_name,
            environment=args.environment,
            proxy_port=args.proxy_port,
        )
        for label, path in paths.items():
            print(f"✅ {label}: {path}")
        return 0
    except SkillError as exc:
        print_error(str(exc))
        return 1
    except Exception as exc:  # noqa: BLE001
        print_error(f"Failed to generate LLM proxy starter: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
