#!/usr/bin/env python3
"""Render Elastic-native starter assets for agent observability."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from common import SkillError, ensure_dir, print_error, read_json, validate_index_prefix, write_json, write_text

SUPPORTED_INGEST_MODES = ("collector", "elastic-agent-fleet", "apm-otlp-hybrid")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render Elastic Agent / Fleet starter assets")
    parser.add_argument("--discovery", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--ingest-mode", choices=SUPPORTED_INGEST_MODES, default="elastic-agent-fleet")
    parser.add_argument("--index-prefix", default="agent-obsv")
    parser.add_argument("--service-name", default="agent-runtime")
    parser.add_argument("--environment", default="dev")
    parser.add_argument("--fleet-server-url", default="")
    parser.add_argument("--fleet-enrollment-token", default="")
    parser.add_argument("--apm-server-url", default="")
    parser.add_argument("--kibana-url", default="")
    parser.add_argument("--otlp-endpoint", default="http://127.0.0.1:4317")
    return parser.parse_args()


def build_policy(discovery: dict[str, Any], *, index_prefix: str, service_name: str, environment: str, ingest_mode: str) -> dict[str, Any]:
    modules = [module.get("module_kind") for module in discovery.get("detected_modules", []) if module.get("module_kind")]
    integrations = [
        {
            "name": "system",
            "package": "system",
            "reason": "Baseline host + process telemetry for the agent runtime host.",
        },
        {
            "name": "custom_logs",
            "package": "logfile",
            "reason": "Catch CLI / runtime logs when the agent does not emit OTLP everywhere.",
        },
    ]
    if any(module in modules for module in ("model_adapter", "tool_registry", "mcp_surface", "runtime_entrypoint")):
        integrations.append(
            {
                "name": "elastic_apm",
                "package": "apm",
                "reason": "Track agent turns, tool spans, and model calls with Elastic APM semantics.",
            }
        )
    if ingest_mode == "apm-otlp-hybrid":
        integrations.append(
            {
                "name": "otlp_bridge",
                "package": "otlp",
                "reason": "Keep OTLP ingress open for agents already instrumented with OpenTelemetry.",
            }
        )
    return {
        "name": f"{service_name}-{ingest_mode}",
        "namespace": environment,
        "description": "Starter Elastic-native policy generated by elasticsearch-agent-observability.",
        "monitoring_enabled": ["logs", "metrics"],
        "index_prefix": validate_index_prefix(index_prefix),
        "service_name": service_name,
        "recommended_signals": discovery.get("recommended_signals", []),
        "recommended_modules": modules,
        "integrations": integrations,
    }


def build_env_template(*, fleet_server_url: str, fleet_enrollment_token: str, apm_server_url: str, otlp_endpoint: str, service_name: str, environment: str) -> str:
    return "\n".join(
        [
            "# Elastic-native runtime defaults",
            f"FLEET_URL={fleet_server_url}",
            f"FLEET_ENROLLMENT_TOKEN={fleet_enrollment_token}",
            f"ELASTIC_APM_SERVER_URL={apm_server_url}",
            f"OTEL_EXPORTER_OTLP_ENDPOINT={otlp_endpoint}",
            f"OTEL_SERVICE_NAME={service_name}",
            f"OTEL_RESOURCE_ATTRIBUTES=deployment.environment={environment},observer.product=elasticsearch-agent-observability",
            "ELASTIC_AGENT_TAGS=agent-observability,elastic-native",
            "",
        ]
    )


def build_run_script(*, ingest_mode: str, env_path: Path) -> str:
    env_name = env_path.name
    if ingest_mode == "elastic-agent-fleet":
        command = (
            'exec "${ELASTIC_AGENT_BIN:-elastic-agent}" enroll '
            '--url "${FLEET_URL}" --enrollment-token "${FLEET_ENROLLMENT_TOKEN}" --non-interactive'
        )
    else:
        command = (
            'exec "${ELASTIC_AGENT_BIN:-elastic-agent}" run '
            '--path.config "$SCRIPT_DIR" --path.home "$SCRIPT_DIR/.elastic-agent-home"'
        )
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            "set -euo pipefail",
            'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
            "set -a",
            f'source "$SCRIPT_DIR/{env_name}"',
            "set +a",
            command,
            "",
        ]
    )


def build_bootstrap_readme(*, ingest_mode: str, kibana_url: str, fleet_server_url: str, apm_server_url: str) -> str:
    lines = [
        "# Elastic-native bootstrap",
        "",
        f"- ingest_mode: `{ingest_mode}`",
        f"- fleet_server_url: `{fleet_server_url or 'set in elastic-agent.env'}`",
        f"- apm_server_url: `{apm_server_url or 'set in elastic-agent.env'}`",
        f"- kibana_url: `{kibana_url or 'optional'}`",
        "",
        "## What this bundle is",
        "",
        "- a starter Elastic Agent / Fleet policy skeleton",
        "- an env template for enrollment and APM / OTLP wiring",
        "- a launcher script for local bootstrap or operator review",
        "",
        "## Important boundary",
        "",
        "This bundle is intentionally render-only. It does not auto-call Fleet APIs or mutate Kibana Fleet state yet.",
    ]
    return "\n".join(lines) + "\n"


def render_assets(
    discovery: dict[str, Any],
    output_dir: Path,
    *,
    ingest_mode: str,
    index_prefix: str,
    service_name: str,
    environment: str,
    fleet_server_url: str,
    fleet_enrollment_token: str,
    apm_server_url: str,
    kibana_url: str,
    otlp_endpoint: str,
) -> dict[str, str]:
    if ingest_mode not in SUPPORTED_INGEST_MODES:
        raise SkillError(f"Unsupported ingest mode: {ingest_mode}")
    ensure_dir(output_dir)
    policy = build_policy(
        discovery,
        index_prefix=index_prefix,
        service_name=service_name,
        environment=environment,
        ingest_mode=ingest_mode,
    )
    env_text = build_env_template(
        fleet_server_url=fleet_server_url,
        fleet_enrollment_token=fleet_enrollment_token,
        apm_server_url=apm_server_url,
        otlp_endpoint=otlp_endpoint,
        service_name=service_name,
        environment=environment,
    )
    env_path = output_dir / "elastic-agent.env"
    launcher_path = output_dir / "run-elastic-agent.sh"
    readme_path = output_dir / "README.md"
    policy_path = output_dir / "elastic-agent-policy.json"

    write_json(policy_path, policy)
    write_text(env_path, env_text)
    write_text(launcher_path, build_run_script(ingest_mode=ingest_mode, env_path=env_path))
    write_text(readme_path, build_bootstrap_readme(ingest_mode=ingest_mode, kibana_url=kibana_url, fleet_server_url=fleet_server_url, apm_server_url=apm_server_url))
    launcher_path.chmod(0o755)
    return {
        "policy": str(policy_path),
        "env": str(env_path),
        "launcher": str(launcher_path),
        "readme": str(readme_path),
    }


def main() -> int:
    try:
        args = parse_args()
        discovery = read_json(Path(args.discovery).expanduser().resolve())
        output_dir = Path(args.output_dir).expanduser().resolve()
        paths = render_assets(
            discovery,
            output_dir,
            ingest_mode=args.ingest_mode,
            index_prefix=args.index_prefix,
            service_name=args.service_name,
            environment=args.environment,
            fleet_server_url=args.fleet_server_url,
            fleet_enrollment_token=args.fleet_enrollment_token,
            apm_server_url=args.apm_server_url,
            kibana_url=args.kibana_url,
            otlp_endpoint=args.otlp_endpoint,
        )
        print(f"✅ Elastic-native assets written to: {output_dir}")
        for name, path in paths.items():
            print(f"   {name}: {path}")
        return 0
    except SkillError as exc:
        print_error(str(exc))
        return 1
    except Exception as exc:  # noqa: BLE001
        print_error(f"Failed to render Elastic-native assets: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
